export const LAYOUT = {
	DEFAULT_RIGHT_SIDEBAR_WIDTH: 320,
	DEFAULT_TIMELINE_HEIGHT: 320,
	MAX_RIGHT_SIDEBAR_WIDTH: 600,
	MAX_TIMELINE_HEIGHT_OFFSET: 200,
	MIN_RIGHT_SIDEBAR_WIDTH: 250,
	MIN_TIMELINE_HEIGHT: 150,
	RIGHT_SIDEBAR_SNAP_THRESHOLD: 50,
} as const;

export const ZOOM = {
	DEFAULT: 50,
	MAX: 200,
	MIN: 10,
} as const;
