[project]
name = "voice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mistral-common>=1.8.1",
    "torch>=2.7.1",
    "torchaudio>=2.7.1",
    "torchvision>=0.22.1",
    "transformers>=4.48.0",
]

[tool.uv.sources]
transformers = { git = "https://github.com/huggingface/transformers.git" }
